### PR TITLE
Add Mod functionality

### PR DESCRIPTION
**Pull request by Boy0000**

### CODE REVIEW

**Comment by Boy0000** [comment]
Currently moves the mods into mod folder, but does not display them in the launcher.

**Comment by Boy0000** [comment]
@0ffz help?

**Review by 0ffz — COMMENTED** [review]
I feel like beyond letting people click a button to add mods, our primary goal should be to list all the mods that are already installed and let you toggle them. If we're installing into our own folder now, perhaps we need options to allow launching with all the mods in `mods` folder as well, or only certain mods (symlinks would be useful here)

**Comment by Boy0000** [comment]
Not sure what you mean?
it does launch the games with all mods in .mineinabyss/mods?
so if people want to add a mod it adds it into .mineinabyss/mods and displays it in another tab in the launcher

**Pull request closed without merging**
